.NET Standard 2.0 conversion
cronofy/cronofy-csharp pull request #81
Opened 2020-03-12 22:11 UTC by Nevett

Converted with minimal changes to the code itself.
- Produces a single .NET Standard 2.0 binary and NuGet package supported by .NET Framework 4.6.1 and Core 2.0
- Small bump to the `Newtonsoft.Json` minimum version
- Changed example project to .NET Core
- Set up a GitHub Action to run the tests
- Template files removed thanks to nicer csproj features.
- Things have moved about a bit in the build, mostly thanks to dotnet CLIs combined build and package command, but the results should be equivalent.
- Brought in icon file per newer Nuget spec.
-  ☹️ Have not yet brought in a replacement for StyleCop. Notable modern equivalents [FxCop](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019) and [StyleCop.Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) both spit out an abundance of issues. Going to chalk that up to a mix of newer conventions and missing the project-specific overrides.

To develop locally, install the latest [dotnet SDK](https://dotnet.microsoft.com/download) and try
```dotnet test
dotnet run --project src/Cronofy.Example```

2020-07-14 00:32 UTC, GreenAirplane commented
Hi @Nevett, any idea on when this pull request can be merged? Let me know if you need any help.

2020-07-17 11:15 UTC, Nevett commented
> Hi @Nevett, any idea on when this pull request can be merged? Let me know if you need any help.

Hey, we are planning to get this merged in still - thanks for reaching out so we can see the demand!

In the short term if you're blocked waiting for this you can actually reference https://www.nuget.org/packages/CronofyCore which is a build of this branch under a different package name which some other customers have been successfully using.

2021-03-18 15:28 UTC, gshutler requested changes
As this is a major version, we can fix the change 🇬🇧 `DataCentre` to be 🇺🇸 `DataCenter` to match standards too.

Would want to mention it in the changelog, should be an easy fix for people if they are using it, and not in that many spots in their code either.

2021-03-18 15:28 UTC, gshutler commented on CHANGELOG.md
> +[#82]: https://github.com/cronofy/cronofy-csharp/pull/81
```suggestion
[#82]: https://github.com/cronofy/cronofy-csharp/pull/82
```

2021-03-18 15:52 UTC, gshutler approved these changes

2021-03-18 16:59 UTC, merged